DISCORD_URL = "https://discord.com/api/v9"

WEDNESDAY = [
    "https://www.youtube.com/watch?v=EaVowG5Y2DI",    
    "https://www.youtube.com/watch?v=PAnKl7862qc",
    "https://www.youtube.com/watch?v=frNFBv2QIoE",
    "https://www.youtube.com/watch?v=Xf_wuAQ-t44",
    "https://www.youtube.com/watch?v=zHpFuOlPrlQ",
    "https://www.youtube.com/watch?v=In9Bs1wiF5s",
    "https://www.youtube.com/watch?v=iTl1l3GFMJ8",
    "https://www.youtube.com/watch?v=7dr2s59XnBE",
    "https://www.youtube.com/watch?v=-R40VcLKyIw",
    "https://www.youtube.com/watch?v=qCsYa8PeVfU",
    "https://www.youtube.com/watch?v=4Sr5pRpDZMk",
    "https://www.youtube.com/watch?v=PE8GlPpuLuY",
    "https://www.youtube.com/watch?v=ZHS5yAwApUs",
    "https://www.youtube.com/watch?v=LrleLDD8CJM",
    "https://www.youtube.com/watch?v=Kz26jod9-cQ",
    "https://www.youtube.com/watch?v=036ItQLi-sQ",
    "https://www.youtube.com/watch?v=ESNBnxtpKqI",
    "https://www.youtube.com/watch?v=IR0QUwGmo4A",
    "https://www.youtube.com/watch?v=N3e7G9OxfhI",
    "https://www.youtube.com/watch?v=meuYC7FP7HU",
    "https://www.youtube.com/watch?v=VzigPnZ8OYE",
    "https://www.youtube.com/watch?v=IaE0g3oVIZ0",
    "https://www.youtube.com/watch?v=NBPlPowAsNc",
    "https://www.youtube.com/watch?v=It8RbsGIe48",
    "https://www.youtube.com/watch?v=VfaNCw2bF48",
    "https://www.youtube.com/watch?v=0W51GIxnwKc",
    "https://www.youtube.com/watch?v=VXc47lVx7Eo",
    "https://www.youtube.com/watch?v=3RSL5k3yZOM",
    "https://www.youtube.com/watch?v=_87k7gxeVsw",
    "https://www.youtube.com/watch?v=VaPMUACYWww",
    "https://www.youtube.com/watch?v=m2Z0CyuyfMI",
    "https://www.youtube.com/watch?v=aew9WTLqjDc",
    "https://www.youtube.com/watch?v=KSwnFzlPEuY",
    "https://www.youtube.com/watch?v=csqJK8wwaHw",
    "https://www.youtube.com/watch?v=fyJGKEswuSc",
    "https://www.youtube.com/watch?v=YSDAAh6Lps4",
    "https://www.youtube.com/watch?v=1CH-7qjz4D4",
    "https://www.youtube.com/watch?v=7aTtNNjIyi4",
    "https://www.youtube.com/watch?v=zl6phK1mXC4",
    "https://www.youtube.com/watch?v=OzQ-KvxLVT0",
    "https://www.youtube.com/watch?v=szqNmefKXxc",
    "https://www.youtube.com/watch?v=Y_xlWdgi1ew",
    "https://www.youtube.com/watch?v=hzGQSlrB1_o",
    "https://www.youtube.com/watch?v=pXv4zQ6dYPQ",
    "https://www.youtube.com/watch?v=EBNEPil4da0",
    "https://www.youtube.com/watch?v=JHO61_wDC30",
    "https://www.youtube.com/watch?v=SePVlroq6AI",
    "https://www.youtube.com/watch?v=oVxFk_IIB2o",
    "https://www.youtube.com/watch?v=gxm5SwfkwcI",
    "https://www.youtube.com/watch?v=DREDJ4fkz-g",
    "https://www.youtube.com/watch?v=Oct2xKMGOno",
    "https://www.youtube.com/watch?v=bbat6cvgEJ8",
    "https://www.youtube.com/watch?v=9K4-jllrPrE"
]

PANIK = "https://i.imgur.com/5W1cV7W.jpeg"

IMAGES = [
    "https://i.imgur.com/EfGWKP7.gif",
    "https://i.imgur.com/jYGVmQK.jpeg",
    "https://i.imgur.com/qSTXRRR.jpeg",
    "https://i.imgur.com/DDUHn9p.mp4",
    "https://i.imgur.com/EW6t8Ts.jpeg",
    "https://i.imgur.com/gja02em.mp4",
    "https://i.imgur.com/V5YdCmT.gif",
    "https://i.imgur.com/FN4Nl9r.mp4",
    "https://i.imgur.com/bnzrm8t.jpeg",
    "https://i.imgur.com/8H7H6iR.jpeg",
    "https://i.imgur.com/Qhr9fZd.jpeg",
    "https://i.imgur.com/WdQCkEu.jpeg",
    "https://i.imgur.com/xvWwInq.gif",
    "https://i.imgur.com/SmRaRr7.mp4",
    "https://i.imgur.com/bXCwF2W.mp4",
    "https://i.imgur.com/VfDOUWm.png",
    "https://i.imgur.com/jTzoG8F.png",
    "https://i.imgur.com/Ra8X62E.jpeg",
    "https://i.imgur.com/3XUEVt3.jpeg",
    "https://i.imgur.com/iZWsMYo.jpeg",
    "https://i.imgur.com/tmOxnZb.jpeg",
    "https://i.imgur.com/3r5IC7E.mp4",
    "https://i.imgur.com/JQmbBXC.jpeg",
    "https://i.imgur.com/jFI8wB9.jpeg",
    "https://i.imgur.com/TSKjOav.jpeg",
    "https://i.imgur.com/TuQpLHw.jpeg",
    "https://i.imgur.com/decU9y5.jpeg"
]

IMAGE_FILE = "added_wednesday.txt"

VIDEO_FILE = "added_dudes.txt"
